### ISSUE TITLE
referenceUploader failing - ':' character is not allowed in the header. Terminating.  

### ISSUE THREAD

**Issue by bwkchee** [PacificBiosciences/SMRT-Analysis#161]
I'm trying to upload a reference with the command: referenceUploader -c -p/path/here -nGRCh38_full -f/data/smrtanalysis/current/common/references_dropbox/GCA_000001405.15_GRCh38_full_analysis_set.fna --ploidy diploid

However I get the following error:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
':' character is not allowed in the header. Terminating.  {File=/data/smrtanalysis/current/common/references_dropbox/GCA_000001405.15_GRCh38_full_analysis_set.fna, HeaderLineNumber=1}

This is the first line of the fasta file and looks like a valid header:
>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38

**Comment by pb-jlandolin** [comment]
I assume you have a ">" for a valid fasta header?


It looks like the problem is with the colons

```
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
':' character is not allowed in the header. Terminating. 
```

I'm also not sure the referenceUploader command alone is sufficient to upload fasta files anymore (it used be).  We have changed the uploading mechanism, so you should try it first in SMRT Portal, and then look in the `jobid/workflow` directory for the appropriate command-line usage.

**Comment by lhon** [comment]
This referenceUploader command currently works:

name=$1
organism=$2
fasta=$3

referenceUploader -c -n "$name" -f $fasta "-o$organism" \
                  --saw="sawriter -blt 8 -welter" \
                  --samIdx="samtools faidx"

Thanks to JohnH for this.
