### ISSUE TITLE
Obtaining workflow.xml for use on the command line

### ISSUE THREAD

**Issue by extemporaneousb** [PacificBiosciences/SMRT-Analysis#167]
Hi PB,

I've just updated from 2.1 to 2.3.1 and I'm realizing that my previous workflows for assembly no longer work, e.g., "compareSequences.py is not supported pbalign_opts must be specified."

What I'd like to do is get a command-line version of the workflow, i.e., all of the module XML code inlined to a single XML document. Or, I'd like to know if there is a mechanism for resolving the XML with all of the common/protocols/blah.xml from the command line, e.g.,

smrtpipe.py --params=RS_HGAP_Assembly.2 ...

If the only way to resolve this is manually inlining, that's fine, I'd just like to know before I go perform that exercise.

thanks, jim

**Comment by lhon** [comment]
The easiest way of getting XML in a single file is to generate the settings.xml by creating jobs from SMRT Portal, and then customizing the settings.xml for a particular analysis. Here are XML files based on SMRT Analysis 2.3:

https://www.dropbox.com/sh/duhw021hzqkwui2/AACdsuQN13uU1IzLPpntSoSPa?dl=0

Also note that in general it’s best not to use XML files based on older versions of SMRT Analysis, since parameters do change between versions, as you have seen, which can affect the results.

**Comment by extemporaneousb** [comment]
I was actually curious if there was a command-line means of doing what Smrtportal does, as I bring up the machine without portal running. However, I can use those files in the dropbox.

**Comment by lhon** [comment]
Unfortunately there isn’t a way to generate those xml files without SMRT Portal at the moment, so the dropbox files would be the easiest way to get them.

**Comment by mjhsieh** [comment]
We can take this offline, I will see what I can do.

**Comment by mjhsieh** [comment]
Jim, I dug out my draft, it was in my old action items... https://gist.github.com/mjhsieh/34a7d7809d20e194e62b
