### ISSUE TITLE
User got ask for root permission doing 2.3.0p2 installation

### ISSUE THREAD

**Issue by mjhsieh** [PacificBiosciences/SMRT-Analysis#174]
@madhubioinfo mentioned that root permission is required for smrtanalysis 2.3.0p2 installation, we would want to know why and see if we can clarify the installation procedure. I suspect that her previous report of smrtpipe execution error is also due to installation problem.

**Comment by madhubioinfo** [comment]
so should i reinstall it again?

**Comment by mjhsieh** [comment]
Dear Mathu, you can try to install again. What is your current Linux distribution/version?

**Comment by madhubioinfo** [comment]
@mjhsieh its CentOS release 5.6 (Final)
Rocks release 5.4.3 (Viper)

**Comment by madhubioinfo** [comment]
@mjhsieh when i install now i get the following error at the end am keeping the entire installation history please find it
 bash smrtanalysis_2.3.0.140936.run -p smrtanalysis-patch_2                                                                                                                .3.0.140936.p2.run --rootdir $SMRT_ROOT
Starting smrtanalysis_2.3.0.140936 self-extraction...
Removing existing install directory (/share/apps/smrtanalysis/install/smrtanalys                                                                                                                is_2.3.0.140936)...
Creating install directory (/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.                                                                                                                140936)...
Extracting smrtanalysis_2.3.0.140936...
Starting smrtanalysis-patch_2.3.0.140936.p2.144836_linux_x86_64_libc-2.5_centos-53 self-extraction...
Creating install directory (/share/apps/smrtanalysis/install/smrtanalysis-patch_2.3.0.140936.p2.144836_linux_x86_64_libc-2.5_centos-53)...
Extracting smrtanalysis-patch_2.3.0.140936.p2.144836_linux_x86_64_libc-2.5_centos-53...
Invoking smrtanalysis-patch_2.3.0.140936.p2.144836_linux_x86_64_libc-2.5_centos-53 installer...
Checking existing version number...
Copying prerun patchfiles...
Invoking smrtanalysis_2.3.0.140936 installer...
                          Welcome to the
             Pacific Biosciences SMRTAnalysis Installer
                   (smrtanalysis_2.3.0.140936)

System sanity check...
----- Part 1 of 7: SMRT Analysis User ----

We recommend running this script as a designated SMRT Analysis user
(e.g. smrtanalysis) who will own all smrtpipe jobs and daemon
processes.

Current user is 'students' (primary group: students)

Use the 'students' as the SMRT Analysis user? [Y/n]: Y

----- Part 2 of 7: System Prerequisite Check -----

Checking various hardware, OS and software related prerequisites...

    LOCALE CHECK: en_US.iso885915
        --> OK: This is an English-language system.
    OS CHECK: "CentOS release 5.6 (Final)"
        --> OK: Fully-supported RedHat/CentOS detected
    Checking preqeuisite OS packages...
        --> OK: Found redhat-lsb
    CPU COUNT: 16
        --> OK: You have at 16 CPUs on this server (required: 8).
    MEM CHECK: Total Memory is 48288 bytes.
        --> OK: You have 3018MB per CPU (required: 1800)

System prerequisites test passed.

----- Part 3 of 7: SMRT Portal DNS -----

The DNS name of the SMRT Analysis host server is used for creating URLs
to access SMRT Portal (e.g. http://myhostname:8080/smrtportal).
The name must resolve in the Domain Name System (DNS) for proper
functionality.  If there is no valid DNS name, then an IP address
should be used.

The following hostnames and IP addresses are recognized by DNS:

Detecting DNS names...
Pick an option:
   1) iicb
   2) iicb.local
   3) 10.1.1.1 (eth0)
   4) 10.10.10.7 (eth1)
   5) Specify an alternate DNS name
Choice [1]: 4

----- Part 4 of 7: SMRT Portal Webserver  ----

SMRT Portal runs a Tomcat webserver which relies on access through
a main port and a shutdown port.  For proper operation, these
ports cannot be used for listening by any other processes.  Select
port numbers which do not conflict with other programs.

Enter the 'main' port for the SMRT Analysis Tomcat Webserver [8080]: 8080
Enter the 'shutdown' port for the SMRT Analysis Tomcat Webserver [8005]: 8005

----- Part 5 of 7: Directory Setup -----

==== TMP Directory Setup ===

Configuring temporary (TMP) directory.  This directory is used
for fast I/O operations, and should be a local directory (not NFS
mounted) with at least enough space to store the data you wish to
analyze.  Setting this to 12Gb is a good start.  This directory must
be available and writable by the smrtanalysis user 'students'
on all nodes in the compute cluster.  It will be created if it
does not exist.

SMRT Analysis will access the TMP directory from this path:

    /share/apps/smrtanalysis/tmpdir

We recommend that it should be a symbolic link pointing to the
real TMP directory.

    The default destination is: /tmp/smrtanalysis
    The current destination is: <unset>  (symlink does not exist)

Enter the symlink destination for the TMP directory [/tmp/smrtanalysis]: /tmp/smrtanalysis
Write access to directory '/tmp/smrtanalysis' validated.

==== USERDATA Directory Setup ===

The USERDATA directory stores information as data is analyzed
and can expand rapidly.  Make sure there is sufficient available
storage in this directory (> 500GB).  This directory must be
available and writable by the smrtanalysis user 'students',
and must be shared on all nodes in the compute  cluster (e.g.
via NFS mount).

SMRT Analysis will access the USERDATA directory from this path:

    /share/apps/smrtanalysis/userdata

This can be a real directory or a symbolic link to a larger storage
location.

Currently this USERDATA location doesn't exist.

Create this directory and continue with installation? [Y/n]: Y
Write access to directory '/share/apps/smrtanalysis/userdata' validated.

----- Part 6 of 7: SMRT Portal Database ----

SMRT Portal uses an internal database in order to keep track of
input SMRT cells, jobs, users, and groups.  No external database
is required.  The database only manages the web-interface and
does not store actual sequence data.


A dedicated TCP port is required to run the database server.
Select a port that does not conflict with any other active
port.  Choosing a port over 50000 is recommended.

Enter the mysql port [53307]: 53307
Ready to create internal database.  Continue? [Y/n]: Y

----- Part 7 of 7: Job Management Cluster Setup -----

What job management system will you be using?

Pick an option:
   1) SGE
   2) LSF
   3) PBS
   4) NONE
Choice [1]: 1

Detecting SGE setup (locations of binaries, SGE_ROOT, SGE_CELL)...

Detected the following settings:
      SGE_ROOT=/opt/gridengine  (from 'SGE_ROOT environment variable')
      SGE_CELL=default          (from 'SGE_CELL environment variable')
      SGE_BINDIR=/opt/gridengine/bin/lx26-amd64         (from 'PATH environment variable')

Are these correct? [Y/n]: Y

Using the following settings:
      SGE_ROOT=/opt/gridengine
      SGE_CELL=default
      SGE_BINDIR=/opt/gridengine/bin/lx26-amd64

Select the queue to use for SMRT Analysis jobs:
Pick an option:
   1) all.q
   2) bs_secondary
Choice [1]: 2

Select the parallel environment to use for SMRT Analysis jobs:
Pick an option:
   1) smp
Choice [1]: 1

An alternate SGE queue may be specified for CeleraAssembler jobs.
The default is to use the same queue.

Use an alternate queue for CeleraAsssember jobs? [y/N]: N

Multiple processors may be used for parallel operations.
The default is one less than the total number of cpus.

Specify number of processors to use for parallel operations (max: 15). [15]: 10

Checking setting for the SGE SMRTAnalysis queue (bs_secondary, smp)...
  Checking that the queue is valid...
  Checking that the pe is valid...
  Checking that the pe is in the queue pe_list...
  Checking the pe allocation_rule...
  Checking the queue hostlist...
  Checking that all queue hosts are execution hosts...
  Checking that all queue hosts are submit hosts...

The following hosts in the hostlist for the SGE SMRTAnalysis queue (bs_secondary)
are not listed as submit hosts (in 'qconf -ss'):
     compute-0-3.local
     compute-0-1.local
     compute-0-2.local
     compute-0-0.local
The list of submit hosts can be listed with:
    qconf -ss
The hostlist for the queue can be listed with:
    qconf -sq bs_secondary | grep hostlist
and host groups listed in the hostlist can be listed with
    qconf -shgrp <host_groupname>
    qconf -shgrp_tree <host_groupname>
    qconf -shgrp_resolved <host_groupname>

The queue execution hosts are required to be submit host in order to run
multiple Celera Assembler sub-jobs in distributed mode.  A single Celera
Assembler job (no sub-jobs) may still be distributed without making that
change.  To change host to submit hosts, select 'n' below and run
'qconf -as <hostname>' before reinvoking.

Continue without modifying the queue host settings? [Y/n]: Y

Applying these settings:
   # ----- Part 1 of 7: SMRT Analysis User -----
   smrt_user=students
   smrt_group=students
   # ----- Part 2 of 7: System Prerequisite Check -----
   # ----- Part 3 of 7: SMRT Portal DNS ------
   smrtportal_dnsname=10.10.10.7
   # ----- Part 4 of 7: SMRT Portal Webserver  -----
   smrtportal_mainport=8080
   smrtportal_shutdownport=8005
   # ----- Part 5 of 6: Directory setup -----
   g_dirs_tmpdir_link=/share/apps/smrtanalysis/tmpdir
   g_dirs_tmpdir_dest=/tmp/smrtanalysis
   dirs_shared_dir=/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/common/userdata/shared_dir
   dirs_userdata_dir=/share/apps/smrtanalysis/userdata
   # ----- Part 6 of 7: SMRT Portal Database -----
   smrtportal_dbuser_admin=root
   smrtportal_dbpasswd_admin=
   smrtportal_dbuser_smrtportal=smrtportal
   smrtportal_dbpasswd_smrtportal=smrtportal
   smrtportal_dbname=smrtportal
   smrtportal_dbhost=127.0.0.1
   smrtportal_dbport=53307
   smrtportal_namedpipeonly=
   # ----- Part 7 of 7: Job Management Cluster Setup -----
   jms_type=SGE
   jms_jobsaredistributed=true
   jms_ca_distribute_pb2ca=useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0
   jms_ca_distribute_hgap=useGrid:0, scriptOnGrid:0, frgCorrOnGrid:0, ovlCorrOnGrid:0
   jms_numprocs=10
   sge_root=/opt/gridengine
   sge_cell=default
   jms_bindir=/opt/gridengine/bin/lx26-amd64
   jms_queue=bs_secondary
   sge_pe=smp
   sge_ca_queue=
   sge_ca_pe=
   sge_use_settings_file=true
Setting up internal database server...
Installing MySQL system tables...
OK
Filling help tables...
OK

To start mysqld at boot time you have to copy
support-files/mysql.server to the right place for your system

PLEASE REMEMBER TO SET A PASSWORD FOR THE MySQL root USER !
To do so, start the server, then issue the following commands:

/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/mysql/bin/mysqladmin -u root password 'new-password'
/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/mysql/bin/mysqladmin -u root -h iicb.sequencer.cluster password 'new-password'

Alternatively you can run:
/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/mysql/bin/mysql_secure_installation

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the manual for more instructions.

You can start the MySQL daemon with:
cd /share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/mysql ; /share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/mysql/bin/mysqld_safe &

You can test the MySQL daemon with mysql-test-run.pl
cd /share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/mysql/mysql-test ; perl mysql-test-run.pl

Please report any problems with the /share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/mysql/scripts/mysqlbug script!

Stopping smrtanalysis mysql server (w/ mysqladmin shutdown)...
Stopping smrtanalysis mysql server (killing pid 17253)...
Current server status: stopped
Starting database server...
  Successfully started database server (pid: 22816)...
mysqld is alive
Securing the database...
Creating the jms.setup.sh file...
Creating the user.settings file...
Creating the user.smrtpipe.rc file...
[INFO]Thu, 19 Feb 2015 13:04:18 - Initiating SMRTAnalysis configuration
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtanalysis-user: smrtanalysis --> students
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtanalysis-group:  --> students
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding configxml-hostname:  --> 10.10.10.7
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding configxml-httpport: 8080 --> 8080
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding configxml-httpsport:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding tomcat-serverxml-shutdownport: 8005 --> 8005
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding tomcat-stop: True --> True
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-webxml-ldapAuthentication:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-webxml-ldapProvider:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-webxml-securityPrincipalTemplate:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-webxml-cmdAuthentication:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-webxml-aws_s3_bucketname:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-webxml-cycleCloudUsageUrl:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-webxml-cycleCloudPaymentUrl:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-webxml-seymourHome: /opt/smrtanalysis --> /opt/smrtanalysis
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-webxml-jobsAreReentrant: true --> true
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-webxml-jobsAreDistributed: false --> true
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-webxml-jobRunCommand: /bin/bash --> /bin/bash
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-webxml-entityManager: smrtportal --> smrtportal
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-persistxml-dbport: 3306 --> 53307
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-persistxml-dbname: smrtportal --> smrtportal
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-persistxml-dbhost: localhost --> 127.0.0.1
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-persistxml-javax.persistence.jdbc.user: smrtportal --> smrtportal
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtportal-persistxml-javax.persistence.jdbc.password: smrtportal --> smrtportal
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-autoAnalysis.instrOutputMax: 100 --> 100
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-autoAnalysis.rollingWindow: 1 --> 1
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-autoAnalysis.batchSize: 1 --> 1
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-autoAnalysis.instrHttpTimeout: 60 --> 60
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-autoAnalysis.intervalInSeconds: 300 --> 300
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-s3.upload.threadsPerProc: 2 --> 2
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-s3.upload.largeFileCutoff: 10MB --> 10MB
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-s3.postTransfer.delete.mode:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-s3.bucket.name:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-s3.access.key:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-s3.secret.key:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-s3.smrtportal.url:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-s3.seymour.home:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding daemon-props-s3.report.dir:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding db-user: root --> root
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding db-pass:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding db-host: localhost --> 127.0.0.1
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding db-port: 3306 --> 53307
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding db-name: smrtportal --> smrtportal
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding smrtpiperc-location:  --> /share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/etc/user.smrtpipe.rc
[INFO]Thu, 19 Feb 20
Fatal error: tomcatd is running. Please stop the service!

Aborting.
15 13:04:18 - Overriding cluster-queue: secondary --> bs_secondary
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding cluster-sge-pe: smp --> smp
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding caspec-queue:  -->
[INFO]Thu, 19 Feb 2015 13:04:18 - Overriding caspec-pe:  -->
installprompter: Error! Encountered unexpected error at 'line 3519 /share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/admin/bin/installprompter', bailing out...

**Comment by mjhsieh** [comment]
The os version/distro should be fine. There is another smrtportal running, is this your old one?

**Comment by madhubioinfo** [comment]
@mjhsieh i have unistalled it and again am trying to install a new one now am receving this as a error

**Comment by mjhsieh** [comment]
there is a tomcat webserver serving on 8080 port. likely the one you "uninstalled". Try to do ```ps auxww|grep 8080``` and see if you see any process.

**Comment by madhubioinfo** [comment]
students  5963  0.0  0.0  61168   692 pts/6    S+   13:41   0:00 grep 8080

**Comment by mjhsieh** [comment]
Or perhaps other stuff is running at port 8080. try again with ```ps auxww|grep tomcat``` or something like that. You might need to consult your local sys administrator for more assistance as well.

**Comment by madhubioinfo** [comment]
now when i tried ps auxx|grep tomcat it gave me the following 
students 11872  0.0  0.0  61168   700 pts/8    S+   14:14   0:00 grep tomcat
students 17357  0.0  0.9 8828768 475656 ?      Sl   Feb12   2:16 /share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/java/bin/java -Djava.util.logging.config.file=/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/tomcat/conf/logging.properties -server -Xmx8g -Djava.library.path=/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/common/lib -Djava.security.auth.login.config=/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/tomcat/conf/kerb5.conf -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.endorsed.dirs=/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/tomcat/endorsed -classpath /share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/tomcat/bin/bootstrap.jar:/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/tomcat/bin/tomcat-juli.jar -Dcatalina.base=/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/tomcat -Dcatalina.home=/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/tomcat -Djava.io.tmpdir=/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/tomcat/temp org.apache.catalina.startup.Bootstrap start

**Comment by madhubioinfo** [comment]
@mjhsieh  i again tried to use it another machine its giving the following error please find it, the installation was successfull on that
[INFO] 2015-02-19 11:08:46,493 Successfully found 3 files in xml:input.xml
[INFO] 2015-02-19 11:08:47,604 smrtpipe.py running on ajeya
[INFO] 2015-02-19 11:08:47,604 SMRT Analysis 2.3.0 / SMRTpipe 1.87.139483
[INFO] 2015-02-19 11:08:49,461 Process id 3314
[INFO] 2015-02-19 11:08:56,306 Starting task://Anonymous/P_Fetch/toFofn
[INFO] 2015-02-19 11:08:56,308 task P_Fetch.toFofn successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 0 slots.
[INFO] 2015-02-19 11:08:56,308 Workflow Completion Status 1/44 in (            2%) tasks completed.
[INFO] 2015-02-19 11:09:01,321 Starting task://Anonymous/P_Fetch/overviewRpt
[INFO] 2015-02-19 11:09:01,322 Starting task://Anonymous/P_Filter/subreads.plsFofn.Scatter
[INFO] 2015-02-19 11:09:01,322 Starting task://Anonymous/P_Fetch/adapterRpt
[INFO] 2015-02-19 11:09:01,327 task P_Filter.subreads.plsFofn.Scatter successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 2 slots.
[INFO] 2015-02-19 11:09:01,328 Workflow Completion Status 2/44 in (            4%) tasks completed.
[ERROR] 2015-02-19 11:09:01,329 *** Failed task task://Anonymous/P_Fetch/overviewRpt
[ERROR] 2015-02-19 11:09:01,329 *** Failed task task://Anonymous/P_Fetch/adapterRpt
[INFO] 2015-02-19 11:09:01,332 Found 2 failed tasks.
[INFO] 2015-02-19 11:09:01,332 task adapterRpt FAILED
[INFO] 2015-02-19 11:09:01,333 task overviewRpt FAILED
Failed smrtpipe version v1.87.139483 with exit code -1 in 16.74 seconds (0.28 minutes)

**Comment by madhubioinfo** [comment]
please find this error
 sudo mkdir $SMRT_ROOT
[sudo] password for students:
Sorry, user students is not allowed to execute '/bin/mkdir
/share/apps/smrtanalysis' as root on iicb.sequencer.cluster

*Mathu Malar C*
*Research Scholar at computational Biology and Genomics Lab,*
*CSIR - Indian Institute of Chemical biology,*
*kolkata-32*

**Comment by mjhsieh** [comment]
Dear Mathu, you should use ```kill -9 17357``` to really stop tomcatd from your previous installation.

**Comment by mjhsieh** [comment]
Hi Mathu,
    This /share/apps folder needs to be visible for all your compute node and the host you installed smrtanalysis on. And where did the "sudo" command come from?

**Comment by madhubioinfo** [comment]
@mjhsieh am done with installation now got like
Applying patch to: /share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936
Checking existing version number...
Checking current patch level...
Checking symlinks...
  Copying prerun files...
Applying patches...
Updating patchlevel file...
Updating patchchnum file...
Updating patchhistory file...
Patch successful.

**Comment by madhubioinfo** [comment]
after installing this i wanted to run HGAP denova for test data got the fowllowing error
[INFO] 2015-02-20 00:07:27,333 Successfully found 3 files in xml:input.xml
[INFO] 2015-02-20 00:07:28,284 smrtpipe.py running on iicb.sequencer.cluster
[INFO] 2015-02-20 00:07:28,284 SMRT Analysis 2.3.0 / SMRTpipe 1.87.139483
[INFO] 2015-02-20 00:07:30,363 Process id 19309
[INFO] 2015-02-20 00:07:37,087 Starting task://Anonymous/P_Fetch/toFofn
[INFO] 2015-02-20 00:07:37,087 task P_Fetch.toFofn successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 0 slots.
[INFO] 2015-02-20 00:07:37,087 Workflow Completion Status 1/44 in (            2%) tasks completed.
[INFO] 2015-02-20 00:07:42,092 Starting task://Anonymous/P_Fetch/adapterRpt
[INFO] 2015-02-20 00:07:42,093 Starting task://Anonymous/P_Filter/filter.plsFofn.Scatter
[INFO] 2015-02-20 00:07:42,093 Starting task://Anonymous/P_Fetch/overviewRpt
[INFO] 2015-02-20 00:07:42,095 task P_Filter.filter.plsFofn.Scatter successfully completed (0.00 sec (0.00 min)). freed 1 slots, using 2 slots.
[INFO] 2015-02-20 00:07:42,095 Workflow Completion Status 2/44 in (            4%) tasks completed.
[ERROR] 2015-02-20 00:07:42,095 *** Failed task task://Anonymous/P_Fetch/overviewRpt
[ERROR] 2015-02-20 00:07:42,096 *** Failed task task://Anonymous/P_Fetch/adapterRpt
[INFO] 2015-02-20 00:07:42,096 Found 2 failed tasks.
[INFO] 2015-02-20 00:07:42,097 task adapterRpt FAILED
[INFO] 2015-02-20 00:07:42,097 task overviewRpt FAILED
Failed smrtpipe version v1.87.139483 with exit code -1 in 16.43 seconds (0.27 minutes)

**Comment by mjhsieh** [comment]
Let's see what's inside of log/P_Fetch/overviewRpt.log

**Comment by madhubioinfo** [comment]
#!/bin/bash
# Setting up SMRTpipe environment
echo "Setting up ENV on $(uname -n)" for task overviewRpt

SEYMOUR_HOME=/share/apps/smrtanalysis/current
source $SEYMOUR_HOME/etc/setup.sh

# Create the local TMP dir if it doesn't exist
tmp_dir=$(readlink -m "/share/apps/smrtanalysis/tmpdir")
if [ ! -e "$tmp_dir" ]; then
   stat=0
   mkdir -p $tmp_dir || stat=$?
   if [[ $stat -ne 0 ]]; then
       echo "SMRTpipe Unable to create TMP dir '/share/apps/smrtanalysis/tmpdir' on $(uname -n)" 1>&2
       exit 1
   else
       echo "successfully created or found TMP dir '/share/apps/smrtanalysis/tmpdir'"
   fi
elif [[ ! -d "$tmp_dir" ]]; then
   echo "SMRTpipe TMP /share/apps/smrtanalysis/tmpdir must be a directory on $(uname -n)" 1>&2
   exit 1
fi

########### TASK metadata #############
# Task            : overviewRpt
# Module          : P_Fetch
# Module Version  : 2.4.139483
# TaskType        : None
# URL             : task://Anonymous/P_Fetch/overviewRpt
# createdAt       : 2015-02-20 00:07:30.345937
# createdAt (UTC) : 2015-02-19 18:37:30.345951
# ncmds           : 2
# LogPath         : /share/apps/smrtanalysis/test_out/log/P_Fetch/overviewRpt.log
# Script Path     : /share/apps/smrtanalysis/test_out/workflow/P_Fetch/overviewRpt.sh

# Input       : /share/apps/smrtanalysis/test_out/input.fofn
# Output      : /share/apps/smrtanalysis/test_out/results/overview.json
#
########### END TASK metadata #############

cd /share/apps/smrtanalysis/test_out/log/P_Fetch
# Writing to log file
cat /share/apps/smrtanalysis/test_out/workflow/P_Fetch/overviewRpt.sh >> /share/apps/smrtanalysis/test_out/log/P_Fetch/overviewRpt.log;
echo "Started on $(date -u)"
echo 'Validating existence of Input Files'
if [ -e /share/apps/smrtanalysis/test_out/input.fofn ]
then
echo 'Successfully found /share/apps/smrtanalysis/test_out/input.fofn'
else
echo 'WARNING: Unable to find necessary input file, or dir /share/apps/smrtanalysis/test_out/input.fofn.'
fi
echo 'Successfully validated input files'

# Task overviewRpt commands:


# Completed writing Task overviewRpt commands


# Task 1
overview_report.py --debug /share/apps/smrtanalysis/test_out/input.fofn /share/apps/smrtanalysis/test_out/results/overview.json || exit $?
echo "Task 1 completed at $(date)"
# Task 2
smrtreporter -basedir /share/apps/smrtanalysis/test_out/results -headinclude /share/apps/smrtanalysis/test_out/results/.martin_header.html --html -o overview.html -rules /share/apps/smrtanalysis/test_out/results/.rules_overview.xml || exit $?
echo "Task 2 completed at $(date)"



rcode=$?
echo "Finished on $(date -u)"
echo "Task overviewRpt with nproc 1 with exit code ${rcode}."
exit ${rcode}# Writing stdout and stderr from Popen:
Setting up ENV on iicb.sequencer.cluster for task overviewRpt
Running task://Anonymous/P_Fetch/overviewRpt on Linux iicb.sequencer.cluster 2.6.18-238.19.1.el5 #1 SMP Fri Jul 15 07:31:24 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux
Started on Thu Feb 19 18:37:37 UTC 2015
Validating existence of Input Files
Successfully found /share/apps/smrtanalysis/test_out/input.fofn
Successfully validated input files
Traceback (most recent call last):
  File "/share/apps/smrtanalysis/current/analysis/bin/overview_report.py", line 8, in <module>
    load_entry_point('pbreports==2.3', 'console_scripts', 'overview_report.py')()
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbreports/report/overview.py", line 57, in main
    return main_runner_default(argv[1:], get_parser(), log)
 File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbsystem/common/cmdline/core.py", line 59, in main_runner_default
    return main_runner(argv, parser, args_executer, setup_log_func, alog)
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbsystem/common/cmdline/core.py", line 36, in main_runner
    args = parser.parse_args(argv)
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/argparse.py", line 1688, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/argparse.py", line 1720, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/argparse.py", line 1929, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/argparse.py", line 1885, in consume_positionals
    take_action(action, args)
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/argparse.py", line 1778, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/argparse.py", line 2204, in _get_values
    value = self._get_value(action, arg_string)
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/argparse.py", line 2233, in _get_value
    result = type_func(arg_string)
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbsystem/common/validators.py", line 86, in validate_fofn
    file_names = bas_fofn_to_bas_files(os.path.abspath(fofn))
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbsystem/common/validators.py", line 108, in fofn_to_files
    raise IOError("Unable to find bas/bax file '{f}'".format(f=bas_file))
IOError: Unable to find bas/bax file 'm140521_060750_42145_c100629372550000001823117509121472_s1_p0.3.bax.h5'

**Comment by mjhsieh** [comment]
the path to h5 files also need to be accessible from the cluster node using the same full path.
So please adjust your input.xml and include the full path for your h5 files and make sure that cluster nodes can see them via the same path.

**Comment by madhubioinfo** [comment]
is it possible to run the fastq filtered subreads with HGAP  assembly?

**Comment by mjhsieh** [comment]
That would be beyond the scope of this issue.

**Comment by madhubioinfo** [comment]
after giving the path of bax.h5 files can run it properly without any hurdle thanks alot for helping me in installing

**Comment by madhubioinfo** [comment]
Traceback (most recent call last):
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 184, in _loadModules
    instance = _dynamicallyLoadModule(moduleName)
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 844, in _dynamicallyLoadModule
    klass = _dynamic_pbinternal_importer(moduleName, upbpy_s)
  File "/share/apps/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 821, in _dynamic_pbinternal_importer
    m = __import__(s)
ImportError: No module named pbinternal.smrtpipe.modules.HybridAssembly

**Comment by mjhsieh** [comment]
This "error" doesn't seem to me from a current version of protocol, can you explain what protocol/settings.xml are you trying to run here? Try add a little bit of text talking about what are you guys doing if possible.

**Comment by mjhsieh** [comment]
sudo was required for user's local design, her school requires a software to stay at /share/apps, however she seemed to use a shared account "students", and apparently her local unix admin already solved this and gave her the right permission to use. Other issue can be brought up if Madhu needs more assistance on "Hybrid Assembly". Madhu, kindly move the question to #176 , thanks. I am closing this as solved by customer.
