### ISSUE TITLE
Packages in SMRT-Analysis

### ISSUE THREAD

**Issue by danshu** [PacificBiosciences/SMRT-Analysis#282]
Hi,

I have installed SMRT-Analysis and I used pbalign to polish my genome. However, the blasr called by pbalign seems didn't have other utils with it, for example, samtoh5.
Here is the error message: "samtoh5 returned a non-zero exit status./bin/sh: 1: samtoh5: not found"
I'm sure that I have blasr in the SMRT-Analysis. However, I can not find "samtoh5" by "locate samtoh5" in the SMRT-Analysis directories. Anyone can help?

Thanks,
Quan

**Comment by ylipacbio** [comment]
Which version of SMRT-Analysis package have you installed? If you have installed v 2.3 (pre 3.0), then executables such as samtoh5 should be in the same bin directory as blasr. e.g. `which blasr`.

In case you have installed v 3.0+, since PacBio has moved from h5 file format to BAM format, then pbalign no longer supports the `bas.h5->sam->cmp.h5->Quiver polishing` pipeline (and executables such as samtoh5 should have be removed from the bin directory). To polish genome, please first convert bas.h5/bax.h5 files to bam and then call the pbalign `unaligned.bam->aligned.bam->Quiver/Arrow polishing` pipeline. You may find useful info [in this wiki page](https://github.com/PacificBiosciences/pbalign/wiki/Mapping-RS-II-reads-(in-movie.bax.h5)-and-calling-consensus-using-pbalign-BLASR-while--sam-option-is-deprecated).

**Comment by danshu** [comment]
I'm using SMRT-Analysis v 3.0+. Thanks for your explanation, which is very useful.

**Comment by smm19900210** [comment]
@danshu , hello, Where is SMRT-Analysis v3.0? I can't seem to find it anywhere. can you give me a address of SMRT-Analysis v3.0? thanks!

**Comment by danshu** [comment]
@smm19900210 
I got SMRT-Analysis v3.0 follwoing this link:
 https://github.com/PacificBiosciences/FALCON_unzip/wiki/FAQ
